/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFab: typeof import('@ionic/vue')['IonFab']
    IonFabButton: typeof import('@ionic/vue')['IonFabButton']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonItemOption: typeof import('@ionic/vue')['IonItemOption']
    IonItemOptions: typeof import('@ionic/vue')['IonItemOptions']
    IonItemSliding: typeof import('@ionic/vue')['IonItemSliding']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonListHeader: typeof import('@ionic/vue')['IonListHeader']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRadio: typeof import('@ionic/vue')['IonRadio']
    IonRadioGroup: typeof import('@ionic/vue')['IonRadioGroup']
    IonRippleEffect: typeof import('@ionic/vue')['IonRippleEffect']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSelect: typeof import('@ionic/vue')['IonSelect']
    IonSelectOption: typeof import('@ionic/vue')['IonSelectOption']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
